# generated by datamodel-codegen:
#   filename:  teteatete.schema.json

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from .references import (
    evaluation_schema,
    global_schema,
    llm_node_for_conversation_schema,
)


class TeteATeteFlowConfig(BaseModel):
    type: Literal["teteatete"]
    name: str
    version: str
    global_: global_schema.GlobalConfig = Field(..., alias="global")
    nodes: List[llm_node_for_conversation_schema.LLMNodeForConversation] = Field(
        ..., max_length=1, min_length=1
    )
    evaluation: Optional[evaluation_schema.EvaluationConfig] = None
