# generated by datamodel-codegen:
#   filename:  references/base_knowledgebase.schema.json

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict


class BaseKnowledgebaseConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    embedding_provider: str
    embedding_model: str
    embedding_model_kwargs: Optional[Dict[str, Any]] = {}
