# generated by datamodel-codegen:
#   filename:  references/code_node.schema.json

from __future__ import annotations

from typing import Dict, Optional

from .base_node_schema import BaseNodeConfig


class CodeNodeConfig(BaseNodeConfig):
    static_argmap: Optional[Dict[str, str]] = None
    validate_when_executing: Optional[bool] = False
    code: str
