# generated by datamodel-codegen:
#   filename:  references/data_entry.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class DataEntry(BaseModel):
    name: str
    secret: Optional[bool] = False
    value: Optional[str] = ""
