# generated by datamodel-codegen:
#   filename:  references/data_source.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Type(Enum):
    s3 = "s3"
    redis = "redis"


class DataSourceConfig(BaseModel):
    type: Type
    source: str
