# generated by datamodel-codegen:
#   filename:  references/filler.schema.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class FillerConfig(BaseModel):
    phrase: List[str]
    frequency: float
    init_delay: float
