# generated by datamodel-codegen:
#   filename:  references/global_llm_node_for_conversation.schema.json

from __future__ import annotations

from typing import Optional

from .llm_node_schema import LLMNodeConfig


class GlobalLLMNodeForConversation(LLMNodeConfig):
    trigger_intent: str
    skip_intent_upon_interruption: Optional[bool] = False
