# generated by datamodel-codegen:
#   filename:  references/global_code_node.schema.json

from __future__ import annotations

from .code_node_schema import CodeNodeConfig


class GlobalCodeNodeConfig(CodeNodeConfig):
    order: int
