# generated by datamodel-codegen:
#   filename:  references/intent_detection.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict

from . import model_schema


class IntentDetectionConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    prompt_template: Optional[str] = None
    model: model_schema.ModelConfig
