# generated by datamodel-codegen:
#   filename:  references/intent_action.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class IntentAction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    intent_instruction: Optional[str] = None
    target_node: Optional[str] = None
