# generated by datamodel-codegen:
#   filename:  references/llm_node_for_workflow.schema.json

from __future__ import annotations

from .llm_node_schema import LLMNodeConfig

LLMNodeForWorkflow = LLMNodeConfig
