# generated by datamodel-codegen:
#   filename:  references/position.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class Position(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: Optional[int] = None
    y: Optional[int] = None
