# generated by datamodel-codegen:
#   filename:  references/redis_knowledgebase.schema.json

from __future__ import annotations

from typing import Optional

from .base_knowledgebase_schema import BaseKnowledgebaseConfig


class RedisKnowledgebaseConfig(BaseKnowledgebaseConfig):
    index: str
    redis_url: Optional[str] = "redis://localhost:6379"
    indexing_algorithm: Optional[str] = "HNSW"
    distance_metric: Optional[str] = "COSINE"
