# generated by datamodel-codegen:
#   filename:  references/transcriber.schema.json

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field

from . import model_schema


class Type(Enum):
    LLM = "LLM"
    AWS = "AWS"
    DEEPGRAM = "DEEPGRAM"


class TranscriberConfig(BaseModel):
    type: Type
    model: Optional[model_schema.ModelConfig] = None
    language: Optional[str] = Field(
        None,
        description="Language code for transcription (e.g., 'en-US', 'es-ES'). If not specified, automatic language detection will be used where supported.",
    )
