# generated by datamodel-codegen:
#   filename:  references/vector_store_node.schema.json

from __future__ import annotations

from typing import Any, Dict, Optional, Union

from . import base_knowledgebase_schema, redis_knowledgebase_schema
from .base_node_schema import BaseNodeConfig


class VectorStoreNodeConfig(BaseNodeConfig):
    kb: Union[
        base_knowledgebase_schema.BaseKnowledgebaseConfig,
        redis_knowledgebase_schema.RedisKnowledgebaseConfig,
    ]
    search_type: Optional[str] = "similarity"
    search_kwargs: Optional[Dict[str, Any]] = {}
