# generated by datamodel-codegen:
#   filename:  references/workflow_edges.schema.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field


class WorkflowEdge(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: str = Field(..., alias="from")
    to: str


class WorkflowEdges(BaseModel):
    workflow_edges: List[WorkflowEdge]
